### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by gilcu3** [fjamour/icentral#1]
I get this error lines after running make, any help would be appreciated. I'm on arch linux gcc 7.2.1.

```
mkdir -p dist/Release/GNU-Linux-x86
mpic++ -o dist/Release/GNU-Linux-x86/fjbc_mpi build/Release/GNU-Linux-x86/src/_bc.o build/Release/GNU-Linux-x86/src/_bc_mem.o build/Release/GNU-Linux-x86/src/bc.o build/Release/GNU-Linux-x86/src/bcc_delta.o build/Release/GNU-Linux-x86/src/bcc_scratch.o build/Release/GNU-Linux-x86/src/bicon.o build/Release/GNU-Linux-x86/src/experiments.o build/Release/GNU-Linux-x86/src/graph_hash_t.o build/Release/GNU-Linux-x86/src/graph_t.o build/Release/GNU-Linux-x86/src/iter_info_t.o build/Release/GNU-Linux-x86/src/main.o build/Release/GNU-Linux-x86/src/mcb_find.o build/Release/GNU-Linux-x86/src/paper_exp.o build/Release/GNU-Linux-x86/src/qube.o build/Release/GNU-Linux-x86/src/subgraph_t.o build/Release/GNU-Linux-x86/src/utility.o  -pthread -std=c++11
build/Release/GNU-Linux-x86/src/bcc_delta.o: In function `bcc_delta_t::i_iteration_2(unsigned int, unsigned int, unsigned int, int, int, std::tr1::unordered_map<unsigned int, double, std::tr1::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, double> > >&)':
bcc_delta.cc:(.text+0x2031): undefined reference to `void subgraph_t::i_fill_map<double>(std::vector<double, std::allocator<double> >&, double)'
bcc_delta.cc:(.text+0x2042): undefined reference to `void subgraph_t::i_fill_map<double>(std::vector<double, std::allocator<double> >&, double)'
build/Release/GNU-Linux-x86/src/qube.o: In function `muc_t::i_iteration_2(unsigned int, unsigned int, unsigned int, int, int, std::tr1::unordered_map<unsigned int, double, std::tr1::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, double> > >&)':
qube.cc:(.text+0x38d1): undefined reference to `void subgraph_t::i_fill_map<double>(std::vector<double, std::allocator<double> >&, double)'
qube.cc:(.text+0x38e2): undefined reference to `void subgraph_t::i_fill_map<double>(std::vector<double, std::allocator<double> >&, double)'
collect2: error: ld returned 1 exit status
```

**Comment by fjamour** [comment]
Can you try to compile with older gcc (4.9)?
If you still get the same problem I'll look into it.

**Comment by gilcu3** [comment]
Yes, it compiles properly on gcc 4.9. I will try fixing the compile problem and make a pull request then. Thanks...

**Comment by gilcu3** [comment]
Pull request added  #2
